project:
  type: website
  output-dir: docs

website:
  title: "NC Offroad"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd  
      - href: overview.qmd
        text: "Brown Mountain OHV Trail system"


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



